- name: APT - Update apt
  apt: update_cache=yes

- name: APT - Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: APT - Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: APT - Remove useless packages from the cache
  apt:
    autoclean: yes

- name: APT - Remove dependencies that are no longer required
  apt:
    autoremove: yes